// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myruovpwvzvttedjggad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15cnVvdnB3dnp2dHRlZGpnZ2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDA3MDQsImV4cCI6MjA2MzA3NjcwNH0.R1OND45ZsEWvH5CUhm-KOmXJ066fAMnBI-dvM6Edys0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);